create database EcommerceDB;
use EcommerceDB;
create table customers ( customers_id int primary key,customername varchar (100),city varchar (50),email varchar(100) );
show tables;
select * from customers;
create table products ( productid int primary key,productname varchar(100),category varchar(50),price decimal(10,2) );
select * from products;
desc customers;
create table orders ( orderid int primary key,customers_id int,orderdate date,foreign key (customers_id) references customers(customers_id) );
select * from orders;
create table orderdetails ( orderdetailid int primary key,orderid int,productid int,quantity int,foreign key (orderid) references orders(orderid),foreign key (productid) references products(productid));
insert into customers values (1,'karan','banglore','karan@gmail.com'),(2,'rahul','chennai','rahul@gmail.com');
select * from customers;
insert into customers values (3,'sanjay','hydrabad','sanjay@gmail.com');
insert into products values (101,'laptop','electronics',50000),(102,'mouse','electronics',500),(103,'keyboard','electronics',1000);
select * from products;
insert into orders values (1001,1,'2025-01-10'),(1002,2,'2025-01-15'),(1003,3,'2025-01-20');
select * from orders;
insert into orderdetails values (1,1001,101,1),(2,1002,102,2),(3,1003,103,3);
select * from orderdetails;
select sum(p.price*od.quantity) as totalsales from orderdetails od join products p on od.productid = p.productid;
select p.productname,sum(od.quantity) as totalsold from products p join orderdetails od on p.productid = od.productid = od.productid group by p.productname order by totalsold desc;
select month(orderdate) as month, count(orderid) as ordercount from orders group by month(orderdate);